### ISSUE TITLE
Consider Tagged Release(s)

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-registry-address#9]
## Use Case

Currently this Go module does not have any release tags, so consumers are stuck with commit-based references to the module:

```text
github.com/hashicorp/terraform-registry-address v0.0.0-20210412075316-9b2996cce896
```

This also can make it more difficult for consumers can use Go module management tooling such as [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) for updates.

## Proposal

Bootstrap a `CHANGELOG.md` and cut a `v0.1.0` tag for starters. When later changes occur, update `CHANGELOG.md` and cut new semantic version tags.

**Comment by bflad** [comment]
@radeksimko how do you feel about this?

**Comment by radeksimko** [comment]
I forgot to bootstrap `CHANGELOG.md`, but also I'm not sure how useful would it be for the initial version.
Either way, `v0.1.0` out: https://github.com/hashicorp/terraform-registry-address/releases/tag/v0.1.0

Thanks for the nudge.
